version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: logistics_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistics_db
      MYSQL_USER: logistics_user
      MYSQL_PASSWORD: logistics_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - logistics_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "logistics_user", "--password=logistics_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: logistics_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://logistics_user:logistics_pass@db:3306/logistics_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - logistics_network

  frontend:
    build: ./frontend
    container_name: logistics_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - logistics_network

networks:
  logistics_network:
    driver: bridge

volumes:
  mysql_data: 