# Generated by Django 4.2.7 on 2025-05-03 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_duration',
            field=models.DurationField(blank=True, help_text='Duração real do serviço', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), help_text='Duração estimada do serviço'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'time'], name='logistics_a_appoint_26fc11_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='logistics_a_status_7fa9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch'], name='logistics_a_branch__4c5897_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['preparer'], name='logistics_a_prepare_745ebb_idx'),
        ),
    ]
