# Generated by Django 4.2.7 on 2025-05-04 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_appointment_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'time'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='logistics_a_appoint_26fc11_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='logistics_a_status_7fa9ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='logistics_a_branch__4c5897_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='logistics_a_prepare_745ebb_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='actual_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preparer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='logistics.userprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10),
        ),
    ]
